import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Heading, Flex, Image } from "@aws-amplify/ui-react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Public Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction={'column'} alignItems={'center'}>
        <Heading level={2}>My Public Page</Heading>
        <Image
          src='/virtual.png'
          height={400}
          alt='Virtual Image'
        />
      </Flex>

    </>
  );
}
